"""
Crm Admin
Generated by CoreX v1.0.0
"""

from django.contrib import admin
from .models import *



@admin.register(Contact)
class ContactAdmin(admin.ModelAdmin):
    list_display = ['full_name', 'email', 'company', 'lead_status', 'created_at']
    list_filter = ['lead_status', 'created_at']
    search_fields = ['first_name', 'last_name', 'email', 'company__name']
    ordering = ['last_name', 'first_name']


@admin.register(Deal)
class DealAdmin(admin.ModelAdmin):
    list_display = ['name', 'contact', 'amount', 'stage', 'probability', 'expected_close_date']
    list_filter = ['stage', 'expected_close_date', 'created_at']
    search_fields = ['name', 'contact__first_name', 'contact__last_name']
    ordering = ['-created_at']


