"""
Seed data management command for wiki
Generated by CoreX v1.0.0
"""

from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from django.utils import timezone
from faker import Faker
import random
from ...models import *


class Command(BaseCommand):
    help = 'Generate seed data for wiki app'
    
    def add_arguments(self, parser):
        parser.add_argument(
            '--count',
            type=int,
            default=10,
            help='Number of records to create'
        )
        parser.add_argument(
            '--clean',
            action='store_true',
            help='Clean existing data before seeding'
        )
    
    def handle(self, *args, **options):
        fake = Faker()
        count = options['count']
        
        if options['clean']:
            self.stdout.write('Cleaning existing data...')
            
            Page.objects.all().delete()
            PageRevision.objects.all().delete()
            
        
        # Create users if they don't exist
        users = list(User.objects.all())
        if len(users) < 5:
            for i in range(5 - len(users)):
                user = User.objects.create_user(
                    username=fake.user_name(),
                    email=fake.email(),
                    password='testpass123',
                    first_name=fake.first_name(),
                    last_name=fake.last_name()
                )
                users.append(user)
        
        
        # Create pages
        for i in range(count):
            page = Page.objects.create(
                title=fake.sentence(),
                slug=fake.slug(),
                content=fake.text(max_nb_chars=2000),
                author=random.choice(users),
                status='published'
            )
            
            # Create revisions
            for j in range(random.randint(1, 3)):
                PageRevision.objects.create(
                    page=page,
                    content=fake.text(max_nb_chars=2000),
                    author=random.choice(users),
                    comment=fake.sentence()
                )
        
        
        
        self.stdout.write(
            self.style.SUCCESS(f'Successfully created seed data for wiki')
        )