"""
Legal Services Models
Generated by CoreX Industry Template v1.0.0
"""

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django_countries.fields import CountryField
from decimal import Decimal


class Attorney(models.Model):
    """Attorney/Lawyer model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='attorney_profile')
    bar_number = models.CharField(max_length=50, unique=True)
    license_state = models.CharField(max_length=100)
    specialization = models.CharField(max_length=200, blank=True)
    years_of_experience = models.PositiveIntegerField(default=0)
    bio = models.TextField(blank=True)
    phone = models.CharField(max_length=20, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Attorney: {self.user.get_full_name()}"
    
    def get_absolute_url(self):
        return reverse('legal:attorney_detail', kwargs={'pk': self.pk})


class Client(models.Model):
    """Client model"""
    CLIENT_TYPES = [
        ('individual', 'Individual'),
        ('corporate', 'Corporate'),
        ('government', 'Government'),
    ]
    
    name = models.CharField(max_length=200)
    client_type = models.CharField(max_length=20, choices=CLIENT_TYPES, default='individual')
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=20, blank=True)
    address = models.TextField(blank=True)
    company_name = models.CharField(max_length=200, blank=True)
    tax_id = models.CharField(max_length=50, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        if self.client_type == 'corporate':
            return f"Corporate Client: {self.company_name}"
        return f"Client: {self.name}"


class Matter(models.Model):
    """Legal matter/case model"""
    STATUS_CHOICES = [
        ('open', 'Open'),
        ('closed', 'Closed'),
        ('pending', 'Pending'),
        ('settled', 'Settled'),
        ('dismissed', 'Dismissed'),
    ]
    
    matter_number = models.CharField(max_length=50, unique=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='matters')
    lead_attorney = models.ForeignKey(Attorney, on_delete=models.CASCADE, related_name='lead_matters')
    assigned_attorneys = models.ManyToManyField(Attorney, related_name='assigned_matters', blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='open')
    practice_area = models.CharField(max_length=100, blank=True)
    date_opened = models.DateField()
    date_closed = models.DateField(blank=True, null=True)
    billing_method = models.CharField(max_length=20, choices=[('hourly', 'Hourly'), ('flat', 'Flat Fee'), ('contingency', 'Contingency')])
    flat_fee_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    contingency_percentage = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Matter: {self.matter_number} - {self.title}"
    
    def get_absolute_url(self):
        return reverse('legal:matter_detail', kwargs={'matter_number': self.matter_number})


class Document(models.Model):
    """Legal document model"""
    DOCUMENT_TYPES = [
        ('contract', 'Contract'),
        ('pleading', 'Pleading'),
        ('discovery', 'Discovery'),
        ('correspondence', 'Correspondence'),
        ('motion', 'Motion'),
        ('brief', 'Brief'),
        ('opinion', 'Opinion'),
        ('other', 'Other'),
    ]
    
    title = models.CharField(max_length=200)
    document_type = models.CharField(max_length=20, choices=DOCUMENT_TYPES, default='other')
    file = models.FileField(upload_to='legal_documents/')
    matter = models.ForeignKey(Matter, on_delete=models.CASCADE, related_name='documents', blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='documents', blank=True, null=True)
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uploaded_documents')
    version = models.CharField(max_length=20, default='1.0')
    is_confidential = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Document: {self.title} ({self.document_type})"


class TimeEntry(models.Model):
    """Time entry for billing"""
    matter = models.ForeignKey(Matter, on_delete=models.CASCADE, related_name='time_entries')
    attorney = models.ForeignKey(Attorney, on_delete=models.CASCADE, related_name='time_entries')
    date = models.DateField()
    hours = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    billing_rate = models.DecimalField(max_digits=10, decimal_places=2)
    is_billed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Time Entry: {self.attorney.user.get_full_name()} - {self.date}"
    
    @property
    def total_amount(self):
        """Calculate total amount for this time entry"""
        return self.hours * self.billing_rate


class Invoice(models.Model):
    """Invoice model"""
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('sent', 'Sent'),
        ('paid', 'Paid'),
        ('overdue', 'Overdue'),
        ('cancelled', 'Cancelled'),
    ]
    
    invoice_number = models.CharField(max_length=50, unique=True)
    matter = models.ForeignKey(Matter, on_delete=models.CASCADE, related_name='invoices')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='invoices')
    date_issued = models.DateField()
    due_date = models.DateField()
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    tax_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Invoice: {self.invoice_number}"


class InvoiceItem(models.Model):
    """Invoice item model"""
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='items')
    description = models.CharField(max_length=200)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f"Invoice Item: {self.description}"


class Court(models.Model):
    """Court model"""
    name = models.CharField(max_length=200)
    court_type = models.CharField(max_length=100)  # e.g., 'District Court', 'Circuit Court'
    jurisdiction = models.CharField(max_length=100)
    address = models.TextField()
    phone = models.CharField(max_length=20, blank=True)
    website = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Court: {self.name}"


class Hearing(models.Model):
    """Court hearing model"""
    matter = models.ForeignKey(Matter, on_delete=models.CASCADE, related_name='hearings')
    court = models.ForeignKey(Court, on_delete=models.CASCADE, related_name='hearings')
    hearing_type = models.CharField(max_length=100)  # e.g., 'Trial', 'Motion Hearing', 'Deposition'
    date = models.DateTimeField()
    duration = models.DurationField(blank=True, null=True)
    location = models.CharField(max_length=200, blank=True)
    judge = models.CharField(max_length=200, blank=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Hearing: {self.hearing_type} for {self.matter.matter_number}"


class Task(models.Model):
    """Task model for legal matters"""
    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('urgent', 'Urgent'),
    ]
    
    title = models.CharField(max_length=200)
    description = models.TextField()
    matter = models.ForeignKey(Matter, on_delete=models.CASCADE, related_name='tasks')
    assigned_to = models.ForeignKey(Attorney, on_delete=models.CASCADE, related_name='assigned_tasks')
    due_date = models.DateField()
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='medium')
    is_completed = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Task: {self.title}"