"""
App configuration for blog app.

Generated by CoreX - Django Scaffolding Framework
"""

from django.apps import AppConfig


class BlogConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'blog'