"""
Blog URLs
Generated by CoreX v1.0.0
"""

from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('category/<slug:slug>/', views.category_detail, name='category_detail'),
]

