"""
Blog Views
Generated by CoreX v1.0.0
"""

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.utils.text import slugify
from .models import *



def post_list(request):
    posts = Post.objects.filter(status='published').select_related('author', 'category')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'blog/list.html', {
        'page_obj': page_obj,
        'posts': page_obj
    })


def post_detail(request, slug):
    post = get_object_or_404(Post, 
                           slug=slug,
                           status='published')
    comments = post.comments.filter(is_approved=True)
    
    # Increment view count
    post.increment_views()
    
    return render(request, 'blog/detail.html', {
        'post': post,
        'comments': comments
    })


def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = category.posts.filter(status='published')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'blog/category_detail.html', {
        'category': category,
        'page_obj': page_obj,
        'posts': page_obj
    })


