"""
Wiki API Serializers
Generated by CoreX v1.0.0
"""

from rest_framework import serializers
from ..models import *



class PageSerializer(serializers.ModelSerializer):
    author = serializers.StringRelatedField(read_only=True)
    
    class Meta:
        model = Page
        fields = ['id', 'title', 'slug', 'content', 'author', 'created_at', 
                 'updated_at', 'is_published']
        read_only_fields = ['created_at', 'updated_at']


class PageRevisionSerializer(serializers.ModelSerializer):
    editor = serializers.StringRelatedField(read_only=True)
    
    class Meta:
        model = PageRevision
        fields = ['id', 'page', 'content', 'editor', 'created_at', 'comment']
        read_only_fields = ['created_at']

