"""
Wiki API Views
Generated by CoreX v1.0.0
"""

from rest_framework import viewsets, status, permissions
from rest_framework.decorators import action
from rest_framework.response import Response
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from ..models import *
from .serializers import *



class PageViewSet(viewsets.ModelViewSet):
    queryset = Page.objects.filter(is_published=True)
    serializer_class = PageSerializer
    lookup_field = 'slug'
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'content']
    ordering_fields = ['title', 'created_at', 'updated_at']
    ordering = ['title']
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    
    def perform_create(self, serializer):
        serializer.save(author=self.request.user)
    
    @action(detail=True, methods=['get'])
    def revisions(self, request, slug=None):
        page = self.get_object()
        revisions = page.revisions.all()
        serializer = PageRevisionSerializer(revisions, many=True)
        return Response(serializer.data)


class PageRevisionViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = PageRevision.objects.all()
    serializer_class = PageRevisionSerializer
    filter_backends = [DjangoFilterBackend, OrderingFilter]
    filterset_fields = ['page']
    ordering = ['-created_at']

