"""
URL Configuration for crm_tailwind_session

Generated by CoreX v1.0.0
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),  # Crm as homepage
    
    path('api/', include('api.urls')),
    
    
    path('accounts/', include('django.contrib.auth.urls')),
    
]

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)