"""
App configuration for social app.

Generated by CoreX - Django Scaffolding Framework
"""

from django.apps import AppConfig


class SocialConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'social'