"""
Social URLs
Generated by CoreX v1.0.0
"""

from django.urls import path
from . import views

app_name = 'social'


urlpatterns = [
    path('', views.feed, name='feed'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<str:username>/', views.follow_user, name='follow_user'),
]

