"""
E-commerce Template Generators
Generated by CoreX Industry Template v1.0.0
"""

import os
import json
from pathlib import Path
from typing import Dict, Any
from jinja2 import Environment, FileSystemLoader


def generate_ecommerce_template(project_path: Path, context: Dict[str, Any]) -> bool:
    """
    Generate E-commerce template files
    
    Args:
        project_path: Path to the project directory
        context: Template context with configuration options
    
    Returns:
        bool: True if generation successful, False otherwise
    """
    try:
        # Get templates directory
        templates_dir = Path(__file__).parent
        env = Environment(loader=FileSystemLoader(str(templates_dir)))
        
        # Create ecommerce app directory
        ecommerce_dir = project_path / "ecommerce"
        ecommerce_dir.mkdir(exist_ok=True)
        
        # Create required subdirectories
        subdirs = ["migrations", "templates/ecommerce", "static/ecommerce/css", "static/ecommerce/js"]
        for subdir in subdirs:
            (ecommerce_dir / subdir).mkdir(parents=True, exist_ok=True)
            
        # Create __init__.py files
        (ecommerce_dir / "__init__.py").touch()
        (ecommerce_dir / "migrations" / "__init__.py").touch()
        
        # Generate models.py (already created)
        # In a real implementation, we would render templates here
        
        # Generate views.py
        views_template = env.get_template("views.py.j2")
        views_content = views_template.render(**context)
        (ecommerce_dir / "views.py").write_text(views_content)
        
        # Generate urls.py
        urls_template = env.get_template("urls.py.j2")
        urls_content = urls_template.render(**context)
        (ecommerce_dir / "urls.py").write_text(urls_content)
        
        # Generate serializers.py for API
        if context.get("api", False):
            serializers_template = env.get_template("serializers.py.j2")
            serializers_content = serializers_template.render(**context)
            (ecommerce_dir / "serializers.py").write_text(serializers_content)
            
            # Create API directory
            api_dir = ecommerce_dir / "api"
            api_dir.mkdir(exist_ok=True)
            (api_dir / "__init__.py").touch()
            
            # Generate API views
            api_views_template = env.get_template("api_views.py.j2")
            api_views_content = api_views_template.render(**context)
            (api_dir / "views.py").write_text(api_views_content)
            
            # Generate API urls
            api_urls_template = env.get_template("api_urls.py.j2")
            api_urls_content = api_urls_template.render(**context)
            (api_dir / "urls.py").write_text(api_urls_content)
        
        # Generate admin.py
        admin_template = env.get_template("admin.py.j2")
        admin_content = admin_template.render(**context)
        (ecommerce_dir / "admin.py").write_text(admin_content)
        
        # Generate forms.py
        forms_template = env.get_template("forms.py.j2")
        forms_content = forms_template.render(**context)
        (ecommerce_dir / "forms.py").write_text(forms_content)
        
        # Generate template files
        template_files = [
            "base.html",
            "product_list.html",
            "product_detail.html",
            "cart.html",
            "checkout.html",
            "order_detail.html",
        ]
        
        for template_file in template_files:
            template = env.get_template(f"templates/{template_file}.j2")
            content = template.render(**context)
            (ecommerce_dir / "templates" / "ecommerce" / template_file).write_text(content)
        
        # Generate static files
        static_files = [
            "style.css",
        ]
        
        for static_file in static_files:
            template = env.get_template(f"static/{static_file}.j2")
            content = template.render(**context)
            (ecommerce_dir / "static" / "ecommerce" / "css" / static_file).write_text(content)
        
        # Generate tests
        tests_dir = ecommerce_dir / "tests"
        tests_dir.mkdir(exist_ok=True)
        (tests_dir / "__init__.py").touch()
        
        test_files = [
            "test_models.py",
            "test_views.py",
            "test_forms.py",
        ]
        
        for test_file in test_files:
            template = env.get_template(f"tests/{test_file}.j2")
            content = template.render(**context)
            (tests_dir / test_file).write_text(content)
        
        # Generate fixtures
        fixtures_dir = project_path / "fixtures"
        fixtures_dir.mkdir(exist_ok=True)
        
        # Create sample data fixtures
        create_sample_fixtures(fixtures_dir, context)
        
        return True
        
    except Exception as e:
        print(f"Error generating E-commerce template: {e}")
        return False


def create_sample_fixtures(fixtures_dir: Path, context: Dict[str, Any]):
    """
    Create sample data fixtures for the E-commerce template
    
    Args:
        fixtures_dir: Path to the fixtures directory
        context: Template context with configuration options
    """
    # Sample categories
    categories = [
        {
            "model": "ecommerce.category",
            "pk": 1,
            "fields": {
                "name": "Electronics",
                "slug": "electronics",
                "description": "Electronic devices and gadgets"
            }
        },
        {
            "model": "ecommerce.category",
            "pk": 2,
            "fields": {
                "name": "Clothing",
                "slug": "clothing",
                "description": "Apparel and fashion items"
            }
        },
        {
            "model": "ecommerce.category",
            "pk": 3,
            "fields": {
                "name": "Home & Garden",
                "slug": "home-garden",
                "description": "Home improvement and garden supplies"
            }
        }
    ]
    
    # Sample products
    products = [
        {
            "model": "ecommerce.product",
            "pk": 1,
            "fields": {
                "name": "Smartphone XYZ",
                "slug": "smartphone-xyz",
                "description": "Latest smartphone with advanced features",
                "category": 1,
                "price": "699.99",
                "compare_price": "799.99",
                "sku": "SP-XYZ-001",
                "quantity": 50,
                "is_active": True,
                "is_featured": True
            }
        },
        {
            "model": "ecommerce.product",
            "pk": 2,
            "fields": {
                "name": "Designer T-Shirt",
                "slug": "designer-t-shirt",
                "description": "Comfortable and stylish designer t-shirt",
                "category": 2,
                "price": "29.99",
                "compare_price": "39.99",
                "sku": "TS-DSN-001",
                "quantity": 100,
                "is_active": True,
                "is_featured": False
            }
        }
    ]
    
    # Write fixtures to files
    with open(fixtures_dir / "ecommerce_categories.json", "w") as f:
        json.dump(categories, f, indent=2)
        
    with open(fixtures_dir / "ecommerce_products.json", "w") as f:
        json.dump(products, f, indent=2)


def main():
    """Main entry point for template generation"""
    import sys
    import argparse
    from pathlib import Path
    
    parser = argparse.ArgumentParser(description="Generate E-commerce template")
    parser.add_argument("project_path", help="Path to the project directory")
    parser.add_argument("--api", action="store_true", help="Include API endpoints")
    
    args = parser.parse_args()
    
    project_path = Path(args.project_path)
    if not project_path.exists():
        print(f"Error: Project path {project_path} does not exist")
        sys.exit(1)
    
    context = {
        "project_name": project_path.name,
        "api": args.api,
    }
    
    if generate_ecommerce_template(project_path, context):
        print("✅ E-commerce template generated successfully!")
        sys.exit(0)
    else:
        print("❌ Failed to generate E-commerce template")
        sys.exit(1)


if __name__ == "__main__":
    main()