"""
App configuration for store app.

Generated by CoreX - Django Scaffolding Framework
"""

from django.apps import AppConfig


class StoreConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'store'