"""
Store URLs
Generated by CoreX v1.0.0
"""

from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
]

