"""
Blog API URLs
Generated by CoreX v1.0.0
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()


router.register('categories', views.CategoryViewSet)
router.register('tags', views.TagViewSet)
router.register('posts', views.PostViewSet)
router.register('comments', views.CommentViewSet)



urlpatterns = [
    path('', include(router.urls)),
]