"""
Forum URLs
Generated by CoreX v1.0.0
"""

from django.urls import path
from . import views

app_name = 'forum'


urlpatterns = [
    path('', views.topic_list, name='topic_list'),
    path('topic/<slug:slug>/', views.topic_detail, name='topic_detail'),
]

