"""
Forum Views
Generated by CoreX v1.0.0
"""

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.utils.text import slugify
from .models import *



def topic_list(request):
    topics = Topic.objects.all().select_related('author', 'category')
    category_slug = request.GET.get('category')
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        topics = topics.filter(category=category)
    
    paginator = Paginator(topics, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    categories = Category.objects.all()
    
    return render(request, 'forum/topic_list.html', {
        'page_obj': page_obj,
        'topics': page_obj,
        'categories': categories
    })


def topic_detail(request, slug):
    topic = get_object_or_404(Topic, slug=slug)
    posts = topic.posts.all().select_related('author')
    
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'forum/topic_detail.html', {
        'topic': topic,
        'page_obj': page_obj,
        'posts': page_obj
    })


