"""
Healthcare Models
Generated by CoreX Industry Template v1.0.0
"""

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from decimal import Decimal
from datetime import date


class Patient(models.Model):
    """Patient model"""
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other'),
        ('prefer_not_to_say', 'Prefer not to say'),
    ]
    
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES)
    blood_type = models.CharField(max_length=5, blank=True)
    phone = PhoneNumberField()
    email = models.EmailField(blank=True)
    address = models.TextField()
    emergency_contact_name = models.CharField(max_length=200, blank=True)
    emergency_contact_phone = PhoneNumberField(blank=True)
    medical_history = models.TextField(blank=True)
    allergies = models.TextField(blank=True)
    current_medications = models.TextField(blank=True)
    insurance_provider = models.CharField(max_length=100, blank=True)
    insurance_policy_number = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Patient: {self.first_name} {self.last_name}"
    
    def get_absolute_url(self):
        return reverse('healthcare:patient_detail', kwargs={'pk': self.pk})
    
    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    @property
    def age(self):
        """Calculate patient age"""
        today = date.today()
        return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))


class MedicalProfessional(models.Model):
    """Medical professional model (doctor, nurse, etc.)"""
    SPECIALTY_CHOICES = [
        ('general_practice', 'General Practice'),
        ('cardiology', 'Cardiology'),
        ('dermatology', 'Dermatology'),
        ('endocrinology', 'Endocrinology'),
        ('gastroenterology', 'Gastroenterology'),
        ('neurology', 'Neurology'),
        ('oncology', 'Oncology'),
        ('orthopedics', 'Orthopedics'),
        ('pediatrics', 'Pediatrics'),
        ('psychiatry', 'Psychiatry'),
        ('radiology', 'Radiology'),
        ('surgery', 'Surgery'),
        ('urology', 'Urology'),
        ('other', 'Other'),
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='medical_profile')
    professional_id = models.CharField(max_length=50, unique=True)  # Medical license number
    specialty = models.CharField(max_length=50, choices=SPECIALTY_CHOICES)
    phone = PhoneNumberField()
    bio = models.TextField(blank=True)
    years_of_experience = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Dr. {self.user.get_full_name()} ({self.specialty})"


class Appointment(models.Model):
    """Medical appointment model"""
    APPOINTMENT_TYPES = [
        ('consultation', 'Consultation'),
        ('follow_up', 'Follow-up'),
        ('procedure', 'Procedure'),
        ('emergency', 'Emergency'),
        ('checkup', 'Regular Checkup'),
    ]
    
    STATUS_CHOICES = [
        ('scheduled', 'Scheduled'),
        ('confirmed', 'Confirmed'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
        ('no_show', 'No Show'),
    ]
    
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='appointments')
    medical_professional = models.ForeignKey(MedicalProfessional, on_delete=models.CASCADE, related_name='appointments')
    appointment_type = models.CharField(max_length=20, choices=APPOINTMENT_TYPES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='scheduled')
    scheduled_date = models.DateTimeField()
    duration = models.DurationField()
    reason = models.TextField()
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Appointment: {self.patient.full_name} with Dr. {self.medical_professional.user.last_name}"


class MedicalRecord(models.Model):
    """Electronic medical record model"""
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='medical_records')
    medical_professional = models.ForeignKey(MedicalProfessional, on_delete=models.CASCADE, related_name='medical_records')
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, related_name='medical_records', blank=True, null=True)
    visit_date = models.DateField()
    diagnosis = models.TextField()
    symptoms = models.TextField()
    treatment = models.TextField()
    prescription = models.TextField(blank=True)
    test_results = models.TextField(blank=True)
    follow_up_instructions = models.TextField(blank=True)
    is_confidential = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Medical Record: {self.patient.full_name} - {self.visit_date}"


class Prescription(models.Model):
    """Prescription model"""
    medical_record = models.ForeignKey(MedicalRecord, on_delete=models.CASCADE, related_name='prescriptions')
    medication_name = models.CharField(max_length=200)
    dosage = models.CharField(max_length=100)
    frequency = models.CharField(max_length=100)  # e.g., "Twice daily"
    duration = models.CharField(max_length=100)  # e.g., "7 days"
    instructions = models.TextField(blank=True)
    is_filled = models.BooleanField(default=False)
    filled_date = models.DateField(blank=True, null=True)
    pharmacy = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Prescription: {self.medication_name} for {self.medical_record.patient.full_name}"


class Insurance(models.Model):
    """Patient insurance model"""
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='insurances')
    provider_name = models.CharField(max_length=200)
    policy_number = models.CharField(max_length=100)
    group_number = models.CharField(max_length=100, blank=True)
    effective_date = models.DateField()
    expiration_date = models.DateField(blank=True, null=True)
    copay_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    is_primary = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Insurance: {self.provider_name} for {self.patient.full_name}"


class Billing(models.Model):
    """Medical billing model"""
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('paid', 'Paid'),
        ('partially_paid', 'Partially Paid'),
        ('overdue', 'Overdue'),
        ('cancelled', 'Cancelled'),
    ]
    
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='bills')
    medical_record = models.ForeignKey(MedicalRecord, on_delete=models.CASCADE, related_name='bills', blank=True, null=True)
    insurance = models.ForeignKey(Insurance, on_delete=models.CASCADE, related_name='bills', blank=True, null=True)
    invoice_number = models.CharField(max_length=50, unique=True)
    service_date = models.DateField()
    description = models.TextField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    due_date = models.DateField()
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Bill: {self.invoice_number} for {self.patient.full_name}"
    
    @property
    def balance_due(self):
        """Calculate remaining balance"""
        return self.amount - self.amount_paid
    
    @property
    def is_overdue(self):
        """Check if bill is overdue"""
        from django.utils import timezone
        return self.status == 'pending' and self.due_date < timezone.now().date()


class Payment(models.Model):
    """Payment model"""
    PAYMENT_METHODS = [
        ('cash', 'Cash'),
        ('credit_card', 'Credit Card'),
        ('debit_card', 'Debit Card'),
        ('insurance', 'Insurance'),
        ('check', 'Check'),
    ]
    
    billing = models.ForeignKey(Billing, on_delete=models.CASCADE, related_name='payments')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHODS)
    transaction_id = models.CharField(max_length=100, blank=True)
    payment_date = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True)
    
    def __str__(self):
        return f"Payment: {self.amount} for Bill {self.billing.invoice_number}"


class Department(models.Model):
    """Medical department model"""
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    head = models.ForeignKey(MedicalProfessional, on_delete=models.SET_NULL, null=True, blank=True, related_name='department_head')
    phone = PhoneNumberField(blank=True)
    location = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Department: {self.name}"


class MedicalInventory(models.Model):
    """Medical inventory model"""
    ITEM_TYPES = [
        ('medication', 'Medication'),
        ('equipment', 'Equipment'),
        ('supply', 'Supply'),
    ]
    
    name = models.CharField(max_length=200)
    item_type = models.CharField(max_length=20, choices=ITEM_TYPES)
    description = models.TextField(blank=True)
    sku = models.CharField(max_length=100, unique=True)
    quantity = models.PositiveIntegerField(default=0)
    reorder_level = models.PositiveIntegerField(default=10)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    supplier = models.CharField(max_length=200, blank=True)
    expiration_date = models.DateField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Inventory: {self.name} ({self.quantity} in stock)"
    
    @property
    def is_low_stock(self):
        """Check if item is low in stock"""
        return self.quantity <= self.reorder_level


class InventoryTransaction(models.Model):
    """Inventory transaction model"""
    TRANSACTION_TYPES = [
        ('purchase', 'Purchase'),
        ('usage', 'Usage'),
        ('adjustment', 'Adjustment'),
        ('return', 'Return'),
    ]
    
    inventory_item = models.ForeignKey(MedicalInventory, on_delete=models.CASCADE, related_name='transactions')
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPES)
    quantity = models.IntegerField()
    unit_cost = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    notes = models.TextField(blank=True)
    performed_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='inventory_transactions')
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Transaction: {self.transaction_type} of {self.quantity} {self.inventory_item.name}"