"""
Seed data management command for crm
Generated by CoreX v1.0.0
"""

from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from django.utils import timezone
from faker import Faker
import random
from ...models import *


class Command(BaseCommand):
    help = 'Generate seed data for crm app'
    
    def add_arguments(self, parser):
        parser.add_argument(
            '--count',
            type=int,
            default=10,
            help='Number of records to create'
        )
        parser.add_argument(
            '--clean',
            action='store_true',
            help='Clean existing data before seeding'
        )
    
    def handle(self, *args, **options):
        fake = Faker()
        count = options['count']
        
        if options['clean']:
            self.stdout.write('Cleaning existing data...')
            
            Contact.objects.all().delete()
            Deal.objects.all().delete()
            
        
        # Create users if they don't exist
        users = list(User.objects.all())
        if len(users) < 5:
            for i in range(5 - len(users)):
                user = User.objects.create_user(
                    username=fake.user_name(),
                    email=fake.email(),
                    password='testpass123',
                    first_name=fake.first_name(),
                    last_name=fake.last_name()
                )
                users.append(user)
        
        
        # Create contacts
        contacts = []
        for i in range(count):
            contact = Contact.objects.create(
                first_name=fake.first_name(),
                last_name=fake.last_name(),
                email=fake.unique.email(),
                phone=fake.phone_number(),
                company=fake.company(),
                contact_type=random.choice(['lead', 'customer', 'prospect'])
            )
            contacts.append(contact)
        
        # Create deals
        for i in range(count // 2):
            Deal.objects.create(
                title=fake.catch_phrase(),
                contact=random.choice(contacts),
                amount=fake.pydecimal(left_digits=5, right_digits=2, positive=True),
                stage=random.choice(['qualification', 'proposal', 'negotiation', 'closed_won', 'closed_lost']),
                probability=fake.random_int(min=10, max=90),
                expected_close_date=fake.future_date()
            )
        
        
        
        self.stdout.write(
            self.style.SUCCESS(f'Successfully created seed data for crm')
        )