"""
ASGI config for demo project.

Generated by CoreX - Django Scaffolding Framework
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'demo.settings')

application = get_asgi_application()