"""
App configuration for forum app.

Generated by CoreX - Django Scaffolding Framework
"""

from django.apps import AppConfig


class ForumConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forum'