"""
Seed data management command for store
Generated by CoreX v1.0.0
"""

from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from django.utils import timezone
from faker import Faker
import random
from ...models import *


class Command(BaseCommand):
    help = 'Generate seed data for store app'
    
    def add_arguments(self, parser):
        parser.add_argument(
            '--count',
            type=int,
            default=10,
            help='Number of records to create'
        )
        parser.add_argument(
            '--clean',
            action='store_true',
            help='Clean existing data before seeding'
        )
    
    def handle(self, *args, **options):
        fake = Faker()
        count = options['count']
        
        if options['clean']:
            self.stdout.write('Cleaning existing data...')
            
            Product.objects.all().delete()
            Category.objects.all().delete()
            Order.objects.all().delete()
            
        
        # Create users if they don't exist
        users = list(User.objects.all())
        if len(users) < 5:
            for i in range(5 - len(users)):
                user = User.objects.create_user(
                    username=fake.user_name(),
                    email=fake.email(),
                    password='testpass123',
                    first_name=fake.first_name(),
                    last_name=fake.last_name()
                )
                users.append(user)
        
        
        # Create categories
        categories = []
        for i in range(5):
            category = Category.objects.create(
                name=fake.word().title(),
                slug=fake.slug(),
                description=fake.text()
            )
            categories.append(category)
        
        # Create products
        for i in range(count):
            Product.objects.create(
                name=fake.catch_phrase(),
                slug=fake.slug(),
                description=fake.text(),
                price=fake.pydecimal(left_digits=3, right_digits=2, positive=True),
                category=random.choice(categories),
                sku=fake.bothify(text='???-###'),
                stock_quantity=fake.random_int(min=0, max=100),
                is_active=True,
                is_featured=fake.boolean(chance_of_getting_true=20)
            )
        
        
        
        self.stdout.write(
            self.style.SUCCESS(f'Successfully created seed data for store')
        )