"""
Real Estate Models
Generated by CoreX Industry Template v1.0.0
"""

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from decimal import Decimal


class Agent(models.Model):
    """Real estate agent model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='agent_profile')
    license_number = models.CharField(max_length=50, unique=True)
    phone = PhoneNumberField()
    bio = models.TextField(blank=True)
    specialties = models.CharField(max_length=200, blank=True)
    years_of_experience = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Agent: {self.user.get_full_name()}"
    
    def get_absolute_url(self):
        return reverse('realestate:agent_detail', kwargs={'pk': self.pk})


class Client(models.Model):
    """Real estate client model"""
    CLIENT_TYPES = [
        ('buyer', 'Buyer'),
        ('seller', 'Seller'),
        ('renter', 'Renter'),
        ('landlord', 'Landlord'),
    ]
    
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = PhoneNumberField()
    client_type = models.CharField(max_length=20, choices=CLIENT_TYPES)
    address = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Client: {self.first_name} {self.last_name}"
    
    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class Property(models.Model):
    """Real estate property model"""
    PROPERTY_TYPES = [
        ('house', 'House'),
        ('apartment', 'Apartment'),
        ('condo', 'Condo'),
        ('townhouse', 'Townhouse'),
        ('land', 'Land'),
        ('commercial', 'Commercial'),
    ]
    
    LISTING_TYPES = [
        ('sale', 'For Sale'),
        ('rent', 'For Rent'),
    ]
    
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('pending', 'Pending'),
        ('sold', 'Sold'),
        ('rented', 'Rented'),
        ('withdrawn', 'Withdrawn'),
    ]
    
    title = models.CharField(max_length=200)
    description = models.TextField()
    property_type = models.CharField(max_length=20, choices=PROPERTY_TYPES)
    listing_type = models.CharField(max_length=10, choices=LISTING_TYPES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')
    
    # Address information
    street_address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    country = CountryField()
    
    # Property details
    price = models.DecimalField(max_digits=12, decimal_places=2)
    bedrooms = models.PositiveIntegerField(blank=True, null=True)
    bathrooms = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True)
    square_feet = models.PositiveIntegerField(blank=True, null=True)
    lot_size = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    year_built = models.PositiveIntegerField(blank=True, null=True)
    parking_spaces = models.PositiveIntegerField(default=0)
    
    # Relationships
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE, related_name='properties')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='properties', blank=True, null=True)
    
    # Timestamps
    listed_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Property: {self.title} ({self.property_type})"
    
    def get_absolute_url(self):
        return reverse('realestate:property_detail', kwargs={'pk': self.pk})
    
    @property
    def full_address(self):
        return f"{self.street_address}, {self.city}, {self.state} {self.zip_code}, {self.country}"


class PropertyImage(models.Model):
    """Property image model"""
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='property_images/')
    caption = models.CharField(max_length=200, blank=True)
    is_main = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Image for {self.property.title}"


class PropertyFeature(models.Model):
    """Property feature model"""
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='features')
    feature_name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    
    def __str__(self):
        return f"{self.feature_name} for {self.property.title}"


class Listing(models.Model):
    """Property listing model"""
    property = models.OneToOneField(Property, on_delete=models.CASCADE, related_name='listing')
    listing_number = models.CharField(max_length=50, unique=True)
    mls_number = models.CharField(max_length=50, blank=True)
    description = models.TextField()
    highlights = models.TextField(blank=True)
    virtual_tour_url = models.URLField(blank=True)
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Listing: {self.property.title}"


class Transaction(models.Model):
    """Real estate transaction model"""
    TRANSACTION_TYPES = [
        ('sale', 'Sale'),
        ('rental', 'Rental'),
        ('lease', 'Lease'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('under_contract', 'Under Contract'),
        ('closed', 'Closed'),
        ('cancelled', 'Cancelled'),
    ]
    
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPES)
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='transactions')
    buyer_client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='buying_transactions', blank=True, null=True)
    seller_client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='selling_transactions', blank=True, null=True)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE, related_name='transactions')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    listing_price = models.DecimalField(max_digits=12, decimal_places=2)
    sale_price = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    commission_rate = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('3.00'))  # Percentage
    commission_amount = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    closing_date = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Transaction: {self.property.title} ({self.transaction_type})"
    
    def calculate_commission(self):
        """Calculate commission amount based on sale price and rate"""
        if self.sale_price:
            self.commission_amount = self.sale_price * (self.commission_rate / 100)
            return self.commission_amount
        return Decimal('0.00')


class Appointment(models.Model):
    """Property showing appointment model"""
    APPOINTMENT_TYPES = [
        ('showing', 'Property Showing'),
        ('meeting', 'Client Meeting'),
        ('inspection', 'Property Inspection'),
        ('closing', 'Closing Meeting'),
    ]
    
    STATUS_CHOICES = [
        ('scheduled', 'Scheduled'),
        ('confirmed', 'Confirmed'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ]
    
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='appointments', blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='appointments')
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE, related_name='appointments')
    appointment_type = models.CharField(max_length=20, choices=APPOINTMENT_TYPES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='scheduled')
    scheduled_date = models.DateTimeField()
    duration = models.DurationField()
    location = models.CharField(max_length=200, blank=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Appointment: {self.appointment_type} on {self.scheduled_date}"


class Inquiry(models.Model):
    """Property inquiry model"""
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='inquiries')
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = PhoneNumberField(blank=True)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Inquiry from {self.name} for {self.property.title}"


class Review(models.Model):
    """Agent review model"""
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE, related_name='reviews')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='reviews_given')
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 6)])  # 1-5 stars
    title = models.CharField(max_length=200)
    comment = models.TextField()
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = ['agent', 'client']
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.rating} stars for {self.agent.user.get_full_name()}"