"""
Crm API Serializers
Generated by CoreX v1.0.0
"""

from rest_framework import serializers
from ..models import *



class ContactSerializer(serializers.ModelSerializer):
    full_name = serializers.ReadOnlyField()
    
    class Meta:
        model = Contact
        fields = ['id', 'first_name', 'last_name', 'full_name', 'email', 
                 'phone', 'company', 'contact_type', 'created_at', 'updated_at']
        read_only_fields = ['created_at', 'updated_at']


class DealSerializer(serializers.ModelSerializer):
    contact = ContactSerializer(read_only=True)
    
    class Meta:
        model = Deal
        fields = ['id', 'title', 'contact', 'amount', 'stage', 'probability', 
                 'expected_close_date', 'created_at', 'updated_at']
        read_only_fields = ['created_at', 'updated_at']

