"""
Crm API Views
Generated by CoreX v1.0.0
"""

from rest_framework import viewsets, status, permissions
from rest_framework.decorators import action
from rest_framework.response import Response
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from ..models import *
from .serializers import *



class ContactViewSet(viewsets.ModelViewSet):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ['contact_type']
    search_fields = ['first_name', 'last_name', 'email', 'company']
    ordering_fields = ['last_name', 'created_at']
    ordering = ['last_name', 'first_name']
    permission_classes = [permissions.IsAuthenticated]


class DealViewSet(viewsets.ModelViewSet):
    queryset = Deal.objects.all()
    serializer_class = DealSerializer
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ['stage', 'contact']
    search_fields = ['title']
    ordering_fields = ['expected_close_date', 'amount', 'created_at']
    ordering = ['-created_at']
    permission_classes = [permissions.IsAuthenticated]

