"""
Forum API Serializers
Generated by CoreX v1.0.0
"""

from rest_framework import serializers
from ..models import *



class CategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        fields = ['id', 'name', 'description', 'created_at']
        read_only_fields = ['created_at']


class TopicSerializer(serializers.ModelSerializer):
    category = CategorySerializer(read_only=True)
    author = serializers.StringRelatedField(read_only=True)
    posts_count = serializers.SerializerMethodField()
    
    class Meta:
        model = Topic
        fields = ['id', 'title', 'category', 'author', 'created_at', 
                 'updated_at', 'is_pinned', 'is_locked', 'posts_count']
        read_only_fields = ['created_at', 'updated_at']
    
    def get_posts_count(self, obj):
        return obj.posts.count()


class PostSerializer(serializers.ModelSerializer):
    topic = TopicSerializer(read_only=True)
    author = serializers.StringRelatedField(read_only=True)
    
    class Meta:
        model = Post
        fields = ['id', 'topic', 'author', 'content', 'created_at', 'updated_at']
        read_only_fields = ['created_at', 'updated_at']

