"""
App configuration for crm app.

Generated by CoreX - Django Scaffolding Framework
"""

from django.apps import AppConfig


class CrmConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'crm'