"""
Crm URLs
Generated by CoreX v1.0.0
"""

from django.urls import path
from . import views

app_name = 'crm'


urlpatterns = [
    path('contacts/', views.contact_list, name='contact_list'),
    path('contacts/<int:contact_id>/', views.contact_detail, name='contact_detail'),
    path('deals/', views.deal_list, name='deal_list'),
]

