"""
Crm Views
Generated by CoreX v1.0.0
"""

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.utils.text import slugify
from .models import *



@login_required
def contact_list(request):
    contacts = Contact.objects.all()
    contact_type = request.GET.get('type')
    
    if contact_type:
        contacts = contacts.filter(contact_type=contact_type)
    
    paginator = Paginator(contacts, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'crm/contact_list.html', {
        'page_obj': page_obj,
        'contacts': page_obj
    })


@login_required
def contact_detail(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    deals = contact.deals.all()
    
    return render(request, 'crm/contact_detail.html', {
        'contact': contact,
        'deals': deals
    })


@login_required
def deal_list(request):
    deals = Deal.objects.all().select_related('contact')
    stage = request.GET.get('stage')
    
    if stage:
        deals = deals.filter(stage=stage)
    
    paginator = Paginator(deals, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'crm/deal_list.html', {
        'page_obj': page_obj,
        'deals': page_obj
    })


