"""
Seed data management command for forum
Generated by CoreX v1.0.0
"""

from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from django.utils import timezone
from faker import Faker
import random
from ...models import *


class Command(BaseCommand):
    help = 'Generate seed data for forum app'
    
    def add_arguments(self, parser):
        parser.add_argument(
            '--count',
            type=int,
            default=10,
            help='Number of records to create'
        )
        parser.add_argument(
            '--clean',
            action='store_true',
            help='Clean existing data before seeding'
        )
    
    def handle(self, *args, **options):
        fake = Faker()
        count = options['count']
        
        if options['clean']:
            self.stdout.write('Cleaning existing data...')
            
            Post.objects.all().delete()
            Topic.objects.all().delete()
            Category.objects.all().delete()
            
        
        # Create users if they don't exist
        users = list(User.objects.all())
        if len(users) < 5:
            for i in range(5 - len(users)):
                user = User.objects.create_user(
                    username=fake.user_name(),
                    email=fake.email(),
                    password='testpass123',
                    first_name=fake.first_name(),
                    last_name=fake.last_name()
                )
                users.append(user)
        
        
        # Create categories
        categories = []
        for i in range(5):
            category = Category.objects.create(
                name=fake.word().title(),
                description=fake.text()
            )
            categories.append(category)
        
        # Create topics
        topics = []
        for i in range(count):
            topic = Topic.objects.create(
                title=fake.sentence(),
                category=random.choice(categories),
                author=random.choice(users),
                is_pinned=fake.boolean(chance_of_getting_true=10)
            )
            topics.append(topic)
        
        # Create posts
        for topic in topics:
            for i in range(random.randint(1, 5)):
                Post.objects.create(
                    topic=topic,
                    author=random.choice(users),
                    content=fake.text(max_nb_chars=1000)
                )
        
        
        
        self.stdout.write(
            self.style.SUCCESS(f'Successfully created seed data for forum')
        )