"""
Wiki Admin
Generated by CoreX v1.0.0
"""

from django.contrib import admin
from .models import *



@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    list_display = ['name', 'slug', 'parent', 'created_at']
    prepopulated_fields = {'slug': ('name',)}
    search_fields = ['name']
    list_filter = ['parent', 'created_at']


@admin.register(Page)
class PageAdmin(admin.ModelAdmin):
    list_display = ['title', 'author', 'status', 'created_at', 'updated_at']
    list_filter = ['status', 'created_at']
    search_fields = ['title', 'content']
    prepopulated_fields = {'slug': ('title',)}
    ordering = ['-updated_at']


@admin.register(PageRevision)
class PageRevisionAdmin(admin.ModelAdmin):
    list_display = ['page', 'author', 'created_at', 'comment']
    list_filter = ['created_at']
    search_fields = ['page__title', 'author__username']
    ordering = ['-created_at']


