"""
Wiki URLs
Generated by CoreX v1.0.0
"""

from django.urls import path
from . import views

app_name = 'wiki'


urlpatterns = [
    path('', views.page_list, name='page_list'),
    path('create/', views.page_create, name='page_create'),
    path('page/<slug:slug>/', views.page_detail, name='page_detail'),
    path('page/<slug:slug>/edit/', views.page_edit, name='page_edit'),
]

