"""
Social API URLs
Generated by CoreX v1.0.0
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()


router.register('profiles', views.ProfileViewSet)
router.register('posts', views.PostViewSet)
router.register('follows', views.FollowViewSet, basename='follow')



urlpatterns = [
    path('', include(router.urls)),
]