"""
App configuration for wiki app.

Generated by CoreX - Django Scaffolding Framework
"""

from django.apps import AppConfig


class WikiConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'wiki'