"""
Crm API URLs
Generated by CoreX v1.0.0
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()


router.register('contacts', views.ContactViewSet)
router.register('deals', views.DealViewSet)



urlpatterns = [
    path('', include(router.urls)),
]