"""
Seed data management command for social
Generated by CoreX v1.0.0
"""

from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from django.utils import timezone
from faker import Faker
import random
from ...models import *


class Command(BaseCommand):
    help = 'Generate seed data for social app'
    
    def add_arguments(self, parser):
        parser.add_argument(
            '--count',
            type=int,
            default=10,
            help='Number of records to create'
        )
        parser.add_argument(
            '--clean',
            action='store_true',
            help='Clean existing data before seeding'
        )
    
    def handle(self, *args, **options):
        fake = Faker()
        count = options['count']
        
        if options['clean']:
            self.stdout.write('Cleaning existing data...')
            
            Post.objects.all().delete()
            Follow.objects.all().delete()
            
        
        # Create users if they don't exist
        users = list(User.objects.all())
        if len(users) < 5:
            for i in range(5 - len(users)):
                user = User.objects.create_user(
                    username=fake.user_name(),
                    email=fake.email(),
                    password='testpass123',
                    first_name=fake.first_name(),
                    last_name=fake.last_name()
                )
                users.append(user)
        
        
        # Create profiles
        for user in users:
            Profile.objects.get_or_create(
                user=user,
                defaults={
                    'bio': fake.text(max_nb_chars=500),
                    'location': fake.city(),
                    'website': fake.url()
                }
            )
        
        # Create follows
        for i in range(count):
            follower = random.choice(users)
            following = random.choice([u for u in users if u != follower])
            Follow.objects.get_or_create(
                follower=follower,
                following=following
            )
        
        # Create posts
        for i in range(count):
            Post.objects.create(
                author=random.choice(users),
                content=fake.text(max_nb_chars=280)
            )
        
        
        
        self.stdout.write(
            self.style.SUCCESS(f'Successfully created seed data for social')
        )