"""
Wiki API URLs
Generated by CoreX v1.0.0
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()


router.register('pages', views.PageViewSet)
router.register('revisions', views.PageRevisionViewSet)



urlpatterns = [
    path('', include(router.urls)),
]