"""
Fintech Models
Generated by CoreX Industry Template v1.0.0
"""

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django_countries.fields import CountryField
from decimal import Decimal
from datetime import date
import uuid


class FinancialInstitution(models.Model):
    """Financial institution model"""
    name = models.CharField(max_length=200)
    institution_type = models.CharField(max_length=100)  # e.g., 'Bank', 'Credit Union', 'Fintech'
    routing_number = models.CharField(max_length=50, unique=True)
    swift_code = models.CharField(max_length=11, blank=True)
    address = models.TextField()
    phone = models.CharField(max_length=20)
    website = models.URLField(blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Institution: {self.name}"


class Account(models.Model):
    """Financial account model"""
    ACCOUNT_TYPES = [
        ('checking', 'Checking'),
        ('savings', 'Savings'),
        ('credit', 'Credit'),
        ('investment', 'Investment'),
        ('loan', 'Loan'),
    ]
    
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        ('frozen', 'Frozen'),
        ('closed', 'Closed'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='accounts')
    institution = models.ForeignKey(FinancialInstitution, on_delete=models.CASCADE, related_name='accounts')
    account_type = models.CharField(max_length=20, choices=ACCOUNT_TYPES)
    account_number = models.CharField(max_length=50, unique=True)
    account_name = models.CharField(max_length=100)
    routing_number = models.CharField(max_length=50)
    current_balance = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0.00'))
    available_balance = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0.00'))
    currency = models.CharField(max_length=3, default='USD')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')
    opened_date = models.DateField()
    closed_date = models.DateField(blank=True, null=True)
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('0.00'))
    credit_limit = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Account: {self.account_name} ({self.account_type})"
    
    def get_absolute_url(self):
        return reverse('fintech:account_detail', kwargs={'pk': self.pk})


class Transaction(models.Model):
    """Financial transaction model"""
    TRANSACTION_TYPES = [
        ('deposit', 'Deposit'),
        ('withdrawal', 'Withdrawal'),
        ('transfer', 'Transfer'),
        ('payment', 'Payment'),
        ('fee', 'Fee'),
        ('interest', 'Interest'),
        ('refund', 'Refund'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('cancelled', 'Cancelled'),
    ]
    
    transaction_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='transactions')
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='completed')
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    currency = models.CharField(max_length=3, default='USD')
    description = models.CharField(max_length=200)
    category = models.CharField(max_length=100, blank=True)
    merchant = models.CharField(max_length=200, blank=True)
    transaction_date = models.DateTimeField()
    posted_date = models.DateTimeField(blank=True, null=True)
    reference_number = models.CharField(max_length=100, blank=True)
    balance_after = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Transaction: {self.transaction_type} of {self.amount} on {self.transaction_date}"


class Transfer(models.Model):
    """Fund transfer model"""
    TRANSFER_TYPES = [
        ('internal', 'Internal Transfer'),
        ('external', 'External Transfer'),
        ('wire', 'Wire Transfer'),
        ('ach', 'ACH Transfer'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('cancelled', 'Cancelled'),
    ]
    
    transfer_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    from_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='outgoing_transfers')
    to_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='incoming_transfers')
    transfer_type = models.CharField(max_length=20, choices=TRANSFER_TYPES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    currency = models.CharField(max_length=3, default='USD')
    description = models.CharField(max_length=200)
    scheduled_date = models.DateTimeField()
    completed_date = models.DateTimeField(blank=True, null=True)
    reference_number = models.CharField(max_length=100, blank=True)
    fee_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Transfer: {self.amount} from {self.from_account} to {self.to_account}"


class Payment(models.Model):
    """Payment model"""
    PAYMENT_METHODS = [
        ('card', 'Credit/Debit Card'),
        ('bank', 'Bank Transfer'),
        ('paypal', 'PayPal'),
        ('crypto', 'Cryptocurrency'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('refunded', 'Refunded'),
        ('cancelled', 'Cancelled'),
    ]
    
    payment_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    payer_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='outgoing_payments')
    payee_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='incoming_payments', blank=True, null=True)
    payee_email = models.EmailField(blank=True)
    payee_name = models.CharField(max_length=200, blank=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHODS)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    currency = models.CharField(max_length=3, default='USD')
    description = models.CharField(max_length=200)
    transaction_date = models.DateTimeField()
    completed_date = models.DateTimeField(blank=True, null=True)
    reference_number = models.CharField(max_length=100, blank=True)
    fee_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Payment: {self.amount} to {self.payee_name or self.payee_email}"


class Budget(models.Model):
    """Budget model"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='budgets')
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    total_amount = models.DecimalField(max_digits=15, decimal_places=2)
    start_date = models.DateField()
    end_date = models.DateField()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Budget: {self.name} ({self.start_date} to {self.end_date})"


class BudgetCategory(models.Model):
    """Budget category model"""
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE, related_name='categories')
    name = models.CharField(max_length=100)
    allocated_amount = models.DecimalField(max_digits=15, decimal_places=2)
    spent_amount = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0.00'))
    color = models.CharField(max_length=7, default='#000000')  # Hex color code
    
    def __str__(self):
        return f"Category: {self.name} in {self.budget.name}"
    
    @property
    def remaining_amount(self):
        """Calculate remaining amount in category"""
        return self.allocated_amount - self.spent_amount
    
    @property
    def percentage_spent(self):
        """Calculate percentage of budget spent"""
        if self.allocated_amount > 0:
            return (self.spent_amount / self.allocated_amount) * 100
        return 0


class ComplianceReport(models.Model):
    """Regulatory compliance report model"""
    REPORT_TYPES = [
        ('kyc', 'Know Your Customer'),
        ('aml', 'Anti-Money Laundering'),
        ('tax', 'Tax Reporting'),
        ('audit', 'Financial Audit'),
    ]
    
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('submitted', 'Submitted'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='compliance_reports')
    report_type = models.CharField(max_length=20, choices=REPORT_TYPES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    report_period_start = models.DateField()
    report_period_end = models.DateField()
    generated_date = models.DateTimeField(auto_now_add=True)
    submitted_date = models.DateTimeField(blank=True, null=True)
    approved_date = models.DateTimeField(blank=True, null=True)
    file = models.FileField(upload_to='compliance_reports/', blank=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Compliance Report: {self.report_type} for {self.user.username}"


class FinancialGoal(models.Model):
    """Financial goal model"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='financial_goals')
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    target_amount = models.DecimalField(max_digits=15, decimal_places=2)
    current_amount = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0.00'))
    target_date = models.DateField()
    is_achieved = models.BooleanField(default=False)
    achieved_date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Goal: {self.name} ({self.current_amount}/{self.target_amount})"
    
    @property
    def progress_percentage(self):
        """Calculate progress percentage"""
        if self.target_amount > 0:
            return (self.current_amount / self.target_amount) * 100
        return 0
    
    @property
    def is_overdue(self):
        """Check if goal is overdue"""
        return not self.is_achieved and self.target_date < date.today()


class InvestmentPortfolio(models.Model):
    """Investment portfolio model"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='investment_portfolios')
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    total_value = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0.00'))
    cash_balance = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0.00'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Portfolio: {self.name} (${self.total_value})"


class Investment(models.Model):
    """Investment holding model"""
    INVESTMENT_TYPES = [
        ('stock', 'Stock'),
        ('bond', 'Bond'),
        ('mutual_fund', 'Mutual Fund'),
        ('etf', 'ETF'),
        ('crypto', 'Cryptocurrency'),
        ('real_estate', 'Real Estate'),
    ]
    
    portfolio = models.ForeignKey(InvestmentPortfolio, on_delete=models.CASCADE, related_name='investments')
    investment_type = models.CharField(max_length=20, choices=INVESTMENT_TYPES)
    symbol = models.CharField(max_length=20, blank=True)
    name = models.CharField(max_length=200)
    quantity = models.DecimalField(max_digits=15, decimal_places=4)
    purchase_price = models.DecimalField(max_digits=15, decimal_places=4)
    current_price = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    purchase_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Investment: {self.name} ({self.quantity} shares)"
    
    @property
    def current_value(self):
        """Calculate current value of investment"""
        if self.current_price:
            return self.quantity * self.current_price
        return self.quantity * self.purchase_price
    
    @property
    def gain_loss(self):
        """Calculate gain/loss on investment"""
        return self.current_value - (self.quantity * self.purchase_price)
    
    @property
    def gain_loss_percentage(self):
        """Calculate gain/loss percentage"""
        if self.purchase_price > 0:
            return ((self.current_price or self.purchase_price) - self.purchase_price) / self.purchase_price * 100
        return 0


class FinancialAlert(models.Model):
    """Financial alert model"""
    ALERT_TYPES = [
        ('low_balance', 'Low Balance'),
        ('large_transaction', 'Large Transaction'),
        ('budget_exceeded', 'Budget Exceeded'),
        ('goal_milestone', 'Goal Milestone'),
        ('payment_due', 'Payment Due'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='financial_alerts')
    alert_type = models.CharField(max_length=20, choices=ALERT_TYPES)
    message = models.CharField(max_length=200)
    is_read = models.BooleanField(default=False)
    triggered_at = models.DateTimeField(auto_now_add=True)
    read_at = models.DateTimeField(blank=True, null=True)
    
    def __str__(self):
        return f"Alert: {self.alert_type} for {self.user.username}"